# Generated by Django 5.2.16 on 2026-07-14 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0002_seed_board_and_statuses'),
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='boards.board')),
            ],
            options={
                'unique_together': {('board', 'name')},
            },
        ),
        migrations.CreateModel(
            name='IssueLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_labels', to='issues.issue')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_labels', to='labels.label')),
            ],
            options={
                'unique_together': {('issue', 'label')},
            },
        ),
    ]
