# Generated by Django 5.2.16 on 2026-07-14 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0002_seed_board_and_statuses'),
        ('issues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('planned_duration', models.PositiveIntegerField(help_text='Duration in days')),
                ('actual_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='boards.board')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_baselines', to='activities.schedulebaseline')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baselines', to='boards.board')),
            ],
        ),
        migrations.CreateModel(
            name='DecisionNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rationale', models.TextField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_nodes', to='boards.board')),
                ('triggered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resulting_baseline', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='activities.schedulebaseline')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successor_links', to='activities.activity')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_links', to='activities.activity')),
            ],
            options={
                'unique_together': {('predecessor', 'successor')},
            },
        ),
        migrations.CreateModel(
            name='ActivityIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_issues', to='activities.activity')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_issues', to='issues.issue')),
            ],
            options={
                'unique_together': {('activity', 'issue')},
            },
        ),
        migrations.CreateModel(
            name='BaselineActivitySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_duration_at_baseline', models.PositiveIntegerField()),
                ('early_start', models.IntegerField()),
                ('early_finish', models.IntegerField()),
                ('late_start', models.IntegerField()),
                ('late_finish', models.IntegerField()),
                ('float', models.IntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='activities.schedulebaseline')),
            ],
            options={
                'unique_together': {('baseline', 'activity')},
            },
        ),
    ]
